<style type="text/css">
.autocomplete-w1:hover{ cursor: pointer;}
.autocomplete-w1 { background:url(img/shadow.png) no-repeat bottom right; position:absolute; top:0px; left:0px; margin:10px 0 0 6px; /* IE6 fix: */ _background:none; _margin:1px 0 0 0; }
.autocomplete {  background:#FFF; cursor:default; text-align:left; max-height:350px; overflow:auto; margin:-6px 6px 6px -6px; /* IE6 specific: */ _height:350px;  _margin:0; _overflow-x:hidden; }
#auto-search a {text-decoration:none; color:#000}
#auto-search:hover { background:#E3EDF2; }
#auto-search{border-bottom:1px solid #C4C6C8;}
.autocomplete div { padding:2px 5px;overflow:hidden;line-height: 18px;text-align:left;}
.autocomplete strong { font-weight:normal; color:#3399FF; } 
.autosearch-img{padding: 3px 8px 8px 0;}
.autosearch-price{color: red;font-family: arial;}
</style>
<form id="search_mini_form" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" method="get">
    <div class="form-search">
        <label for="search"><?php echo $this->__('Search:') ?></label>
        <input id="search" autocomplete="OFF" type="text" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>" value="<?php echo $this->helper('catalogsearch')->getEscapedQueryText() ?>" class="input-text" />
        
        <button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><span><span><?php echo $this->__('Search') ?></span></span></button>
        <div id="search_autocomplete" class="search-autocomplete"></div>
        <script type="text/javascript">
        //<![CDATA[
            var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->helper('autosuggestion')->getSearchBoxDefaultText() ?>');
            var options, a;
            jQuery(function(){
             	options = { 
                     	serviceUrl:'<?php echo $this->helper('autosuggestion')->getSuggestUrl() ?>',
                     	minChars:2
                     	  };
             	
              	a = jQuery('#search').autocomplete(options);
              	jQuery(".autocomplete-w1").click(function(){ 
                  	var selectedString = jQuery('#search').val();
                  	var stringCollection = selectedString.split("<!---->");
                  	if(stringCollection[0] =="No results found"){
                  		jQuery("#search").val("");
                  		jQuery("#search").focus();
                  	}
					else
                  		jQuery("#search").val(stringCollection[1]);
				});
            });
            
        //]]>
        </script>
    </div>
</form>
